// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzljqmvgacusjabfnacg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6bGpxbXZnYWN1c2phYmZuYWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzQ4NjQsImV4cCI6MjA2MDM1MDg2NH0.ryIiL29tzHKQ_V63xlS7ipHT1zuoyXsGCzkOuVEc45c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);